### ISSUE TITLE
If user takes more than one lunch (unlikely but possible) under same abbrev, errors thrown

### ISSUE THREAD

**Issue by minorsecond** [minorsecond/Timeclock#31]
Traceback (most recent call last):
  File "tc.py", line 376, in <module>
    main_menu()
  File "tc.py", line 358, in main_menu
    main_menu()
  File "tc.py", line 362, in main_menu
    break_submenu()
  File "tc.py", line 130, in break_submenu
    breaktime(answer)
  File "tc.py", line 207, in breaktime
    main_menu()
  File "tc.py", line 362, in main_menu
    break_submenu()
  File "tc.py", line 130, in break_submenu
    breaktime(answer)
  File "tc.py", line 189, in breaktime
    diff = datetime.datetime.strptime(start_time, '%I:%M %p') - datetime.datetime.strptime(curr_time, '%I:%M %p')
TypeError: must be string, not None

**Comment by minorsecond** [comment]
Fixed.
